### ISSUE TITLE
[Feature Request] Flatpak for CraftOS-PC-Accelerated

### ISSUE THREAD

**Issue by Commandcracker** [flathub/cc.craftos_pc.CraftOS-PC#6]
I would like to have [CraftOS-PC-Accelerated / CraftOS-PC-luajit](https://github.com/MCJack123/craftos2/tree/luajit) as a Flatpak, but I don't have the Flatpak knowledge to do it my self. It should only need minor changes, It's basically changing the branch and some small things. This might help as a reference: [craftos-pc-accelerated.spec](https://github.com/Commandcracker/craftos2-rpm/blob/main/craftos-pc-accelerated.spec).

**Comment by ninjawarrior1337** [comment]
Alright, I've submitted a PR to the Flathub folks here: https://github.com/flathub/flathub/pull/4173

I'll keep this issue open until that PR closes over there.

**Comment by ninjawarrior1337** [comment]
https://flathub.org/apps/details/cc.craftos_pc.CraftOS-PC-Accelerated
